Lin Alg in Python

In [2]:
import numpy as np

In [3]:
v = np.array([1,2,3])
v2 = np.array([4,5,6])

In [4]:
print(v)
print(v2)

[1 2 3]
[4 5 6]


In [6]:
A = np.array([[2,1],[1,2]])
e_value, e_vectors = np.linalg.eig(A)

In [7]:
print(e_value)
print(e_vectors)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
